### ISSUE TITLE
In Network DAO proposal detail page, switch MainChain to SideChain will enter error page

### ISSUE THREAD

**Issue by daojoer** [TomorrowDAOProject/tomorrowDAO-interface#192]
Step:
1. Enter Network DAO proposal detail page
2. Switch MainChain to SideChain

Result:
Enter to a error page
<img width="1428" alt="image" src="https://github.com/TomorrowDAOProject/tomorrowDAO-interface/assets/167854655/233016a9-f749-4fa8-b361-b2c85ef49c8e">

Proposed changes：
In Network DAO, In any pages, when switch MainChain to SideChain, or switch SideChain to MainChain, should jump to proposals list page

**Comment by currymz** [comment]
Great idea, same as a browser

**Comment by daojoer** [comment]
Fixed confirm
