### ISSUE TITLE
An explorer button is missing to the right of the top bar, and the gray box should not be displayed

### ISSUE THREAD

**Issue by curlconverter-tian** [TomorrowDAOProject/tomorrowDAO-interface#310]
### Description
An explorer button is missing to the right of the top bar, and the gray box should not be displayed

### Steps To Reproduce
1. Open the home page and view the top bar
2. 
### Current Behavior
- 
![img_v3_02d4_fb98512b-0bad-4ec0-9d42-03157edf21hu](https://github.com/user-attachments/assets/620e445e-2fcd-4f37-888a-e180810e12bc)

### Expected Behavior
The explorer button is displayed on the right side of the top bar

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by currymz** [comment]
The explorer button can appear now. but gray box Cannot be reproduced
