### ISSUE TITLE
Log in with portkey plugin, will display many log in success toasts

### ISSUE THREAD

**Issue by daojoer** [TomorrowDAOProject/tomorrowDAO-interface#599]
### Description
Log in with portkey plugin, will display many log in success toasts.

### Steps To Reproduce
1. Log in with portkey plugin
2. Enter a DAO detail page

### Current Behavior
- Will display many log in success toasts
![img_v3_02fl_ae5d33f9-25d2-4a0b-8c15-f344518c67hu](https://github.com/user-attachments/assets/2680c548-4188-4a4a-ac77-bbfe9771d3ce)

### Expected Behavior
- Log in success toast only need display once

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by currymz** [comment]
fixed
