### ISSUE TITLE
When create a list, upload banner, logo, images didn't limit file type

### ISSUE THREAD

**Issue by daojoer** [TomorrowDAOProject/tomorrowDAO-interface#617]
### Description
When create a list, upload banner, logo, images didn't limit file type.

### Steps To Reproduce
1. Log in...
2. Enter Votigram DAO
3. Create a standard list
4. upload banner

### Current Behavior
- When upload banner, logo, images, didn't limit file type, can choose pdf

### Expected Behavior
- When upload banner, logo, images, should limit file type, only can choose PNG, JPEG, JPG

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by currymz** [comment]
fixed

**Comment by daojoer** [comment]
fixed confirm
