### ISSUE TITLE
When create a list, add a option link, didn't check url whether legal

### ISSUE THREAD

**Issue by daojoer** [TomorrowDAOProject/tomorrowDAO-interface#618]
### Description
When create a list, add a option link, didn't check url whether legal.

### Steps To Reproduce
1. Enter Votigram DAO
2. Create a standard list
3. Option link type "dsfsdfsdf"

### Current Behavior
- Didn't check url whether legal
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/1ffd23b5-29d4-4fcf-bfe5-6991a56261e3">

### Expected Behavior
- Should check url whether legal, if not, tips "Please enter a correct link."

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by currymz** [comment]
fixed

**Comment by daojoer** [comment]
fixed confirm
