### ISSUE TITLE
Chain name modification

### ISSUE THREAD

**Issue by currymz** [TomorrowDAOProject/tomorrowDAO-interface#667]
### Expected Behavior
MainChain AELF is changed to aelf MainChain, and SideChain tDVV is changed to aelf dAppChain.

### Specifications
Unify the chain names of all dapps of aelf.

**Features:**
describe feature details here.

**Development Tasks:**
- [x] MainChain AELF is changed to aelf MainChain
- [x] SideChain tDVV is changed to aelf dAppChain

### Dependencies
null

### References
null

**Comment by evan-spidy** [comment]
Resolved in #668
