### ISSUE TITLE
In Referral page, click Leaderboard 'View More' button, if list too long, will not display close button

### ISSUE THREAD

**Issue by daojoer** [TomorrowDAOProject/tomorrowDAO-interface#737]
### Description
In Referral page, click Leaderboard 'View More' button, if list too long, will not display close button.

### Steps To Reproduce
1. Enter Referral page
2. Click Leaderboard 'View More' button

### Current Behavior
- if list too long, will not display close button
- 
![img_v3_02gs_663d6a69-9b28-44a6-9e83-7b9f2c58cfhu](https://github.com/user-attachments/assets/1f72b4ed-ff6e-48a2-ba18-6d4cb79b6a94)

### Expected Behavior
- View More drawer should fixed height

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by evan-spidy** [comment]
Release in #735
